name: php
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
- name: build
  steps:
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker-registry:5000/project/image:latest
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml