name: php
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
- name: build
  steps:
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster
    when:
      branch:
        include: ["conditionno","master"]
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster2
- name: build2
  steps:
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster3
    when:
      branch:
        exclude: ["conditon"]
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster4
- name: build3
  steps:
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster5
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster6
  when:
    branch:
      include: ["a","b"]
