name: php
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
- name: build
  steps:
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hiinmaster
- name: build image
  steps:
  - buildImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/nginx:latest
- name: push image
  steps:
  - pushImageConfig:
      tag: test/nginx:latest
      registry: reg.cnrancher.com
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
