name: php
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branchCondition: all
- name: build
  steps:
  - runScriptConfig:
      image: "php:latest"
      isShell: true
      shellScript: echo "mysss is: $MYSSS" && sleep 300 
      #envFrom:
      #- sourceName: api-key
      #  sourceKey: MYSSS
