name: php
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branchCondition: all
- name: build
  steps:
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo ${mys}
      secrets: ["mys"]
