stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline/dev
      pushRemote: true
      registry: reg.cnrancher.com
    env:
      MIRROR: https://registry.docker-cn.com
