stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: |-
        echo hiaaa
        sleep 1
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: project/test
    env:
      MIRROR: "https://registry.docker-cn.com"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
