stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline/dev
      pushRemote: true
      registry: reg.cnrancher.com
    env:
      PLUGIN_BUILD_ARGS: abc=aaa
      PLUGIN_BUILD_ARGS: def=bbb
