stages:
- name: Build something
  # Conditions for stages
  when:
    branch: set
    event: [ push, pull_request ]
  # Multiple steps run concurrently
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo ${FIRST_KEY} && echo ${ALIAS_ENV}
    # Set environment variables in container for the step
    env:
      FIRST_KEY: VALUE
      SECOND_KEY: VALUE2
    # Set environment variables from project secrets
    envFrom:
    - sourceName: pipeline-secret
      sourceKey: admin-user
      targetKey: ALIAS_ENV
  - runScriptConfig:
      image: busybox
      shellScript: date -R
    # Conditions for steps
    when:
      branch: [ master, dev ]
      event: push
    #Run in privileged mode
    privileged: true
- name: Publish my image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher/busybox:v0.0.0
      # Optionally push to remote registry
      # pushRemote: true
      # registry: reg.example.com
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
# Optional branch conditions for the pipeline 
branch:
  include: [ master, feature/*, set]
  exlclude: [ dev ]
