stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: |-
        echo hi
        exit 1
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: project/test
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
