stages:
- name: a
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: ls
  when:
    branch:
      include:
      - a
      exclude:
      - b
    event:
      include:
      - pull_request
      exclude:
      - push
- name: b
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: ls
    env:
      ss: ss
    privileged: true
    when:
      branch:
        include:
        - aa
        exclude:
        - bb
      event:
        include:
        - pull_request
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: asdfasdf
  - applyYamlConfig:
      path: ./deployment.yaml
    env:
      aa: bbb
