stages:
invalid line
- name: Build something
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo ${FIRST_KEY} && echo ${ALIAS_ENV}
    env:
      FIRST_KEY: VALUE
      SECOND_KEY: VALUE2
    envFrom:
    - sourceName: pipeline-secret
      sourceKey: admin-user
      targetKey: ALIAS_ENV
  - runScriptConfig:
      image: busybox
      shellScript: date -R
    privileged: true
    when:
      branch:
        include:
        - master
        - dev
      event:
        include:
        - push
  - runScriptConfig:
      image: golang:latest
      shellScript: ls
  when:
    branch:
      include:
      - set
    event:
      include:
      - push
      - pull_request
- name: Publish my image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher/busybox:v0.0.0
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - master
  - feature/*
  - set
