stages:
- name: clone
  steps:
  - sourceCodeConfig: {}
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: |-
        echo helloworld
        echo hehe
    env:
      A: B
    envFrom:
    - sourceName: pipeline-secret
      sourceKey: admin-user
      targetKey: AA
    privileged: true
